language: java

jdk: openjdk11
dist: trusty
install: true

services:
  - docker

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: bash docker_push.sh
#    on:
#      tags: true
#  - provider: script
#    skip_cleanup: true
#    script: bash docker_push.sh
#    on:
#      branch: master

script:
  - chmod +x ./gradlew
  - ./gradlew clean bootJar
  - bash docker_push.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/