# 本文件由gmt-meta-scan于 2018-07-09 16:08:02 自动生成
# 可以通用的Dockerfile
FROM openjdk:11.0.2-jdk-slim-stretch

#创建应用目录，并修改时区为中国
RUN mkdir /app && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

WORKDIR /app

CMD java $JAVA_OPTS -jar -server /app/app.jar

COPY ./build/libs/*.jar /app/app.jar